package Models.Pedagógico.Enum;

public enum TipoOcorrencia
{
    BAIXO_DESEMPENHO,
    DIFICULDADE_DE_INTERPRETACAO,
    DIFICULDADE_ORAL,
    DIFICULDADE_ESCRITA,
    BAIXA_PARTICIPACAO_EM_AULAS,
    PROGRESSO_LENTO,
    NAO_REALIZA_ATIVIDADES,
    NAO_ENTREGA_TAREFAS,
    DESCUMPRIMENTO_DE_PRAZOS,
    RITMO_INCOMPATIVEL_COM_A_TURMA,
    NAO_TRAZ_MATERIAL,

    MAU_COMPORTAMENTO,
    DESRESPEITO_A_PROFESSOR,
    DESRESPEITO_A_COLEGAS,
    USO_INDEVIDO_DO_CELULAR,
    CONVERSAS_EXCESSIVAS,
    INTERRUPSOES_CONSTANTES,
    AGRESSIVIDADE_VERBAL,
    AGRESSIVIDADE_FISICA,
    DESINTERESSE_TOTAL,
    DESMOTIVACAO,

    FALTAS_EXCESSIVAS,
    FREQUENCIA_IRREGULAR,
    ATRASO_RECORRENTE,
    SAIDA_ANTECIPADA,
    RISCO_DE_EVASAO,
    ABANDONO_IMINENTE,

    PENDENCIA_FINANCEIRA_AFETANDO_FREQUENCIA,
    NECESSIDADE_DE_ATENDIMENTO_INDIVIDUAL,
    SOLICITACAO_DE_REAVALIACAO,
    TROCA_DE_HORARIO_POR_INCOMPATIBILIDADE,
    DESACORDO_COM_REGRAS_DA_ESCOLA,
    CONFLITO_FAMILIAR_INTERFERING_NO_APROVEITAMENTO
}
